server:
  port: 7001

#eureka配置
eureka:
  instance:
    hostname: localhost  #Eureka服务端的实例名称


  #    public static final String PREFIX = "eureka.client";
  #    public static final String DEFAULT_URL = "http://localhost:8761/eureka/";
  #    public static final String DEFAULT_ZONE = "defaultZone";
  #    private static final int MINUTES = 60;
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #fetch-registry如果为false, 则表示自己为注册中心
    service-url:  #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/