server:
  port: 3344

spring:
  application:
    name: springcloud-config-server

    # 链接远端仓库
  cloud:
    config:
      server:
        git:
          uri: https://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@github.com/JianGuoBaoBao/java_upgrade.git
