server:
    port: 8001

#mybatis 配置
mybatis:
  typeAliasesPackage: com.kuang.springcloud.pojo
  configLocation: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:mybatis/mapper/*.xml

#spring配置
spring:
  application:
    name: springcloud-provier-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
