# 在我们配置文件中能配置的东西， 都存在一个固有的规律
#xxxAutoConfiguration： 默认值 xxxProperties 和配置文件绑定， 我们就可以使用自定义的配置了;

#debug: true

#spring:
#  mvc:
#    static-path-pattern:

#spring:
#  mvc:
#    favicon:
#      enabled: false

