server:
    port: 8001

#mybatis 配置
mybatis:
  typeAliasesPackage: com.kuang.springcloud.pojo
  configLocation: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:mybatis/mapper/*.xml

#spring配置
spring:
  application:
    name: springcloud-provier-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: duixiang


#Eureka的配置： 服务注册到哪里
eureka:
  server:
    enable-self-preservation: false #禁用自我保护模式
  client:
    service-url:  #监控页面
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8001  #修改eureka上默认的描述信息

#info配置
info:
  app.name: kuangshen-springcloud
  company.name: blog.kuangstudy.com
